# This file is part of addfips.
# http://github.com/fitnr/addfips

# Licensed under the GPL-v3.0 license:
# http://opensource.org/licenses/GPL-3.0
# Copyright (c) 2016, fitnr <fitnr@fakeisthenewreal>

language: python

python:
    - 3.6
    - 3.7
    - 3.8
    - pypy3

install:
    - python setup.py install

script:
    - python -m unittest tests/*.py
